<Workspace Version="1.3.0.875" X="-2804.68571525169" Y="-1060.73596585555" zoom="0.885296094758398" ScaleFactor="1" Name="Home" Description="" RunType="Automatic" RunPeriod="100" HasRunWithoutCrash="True">
  <NamespaceResolutionMap />
  <Elements>
    <CoreNodeModels.Input.DoubleInput guid="74d35359-3433-4163-be01-54e328bd06de" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="3415.60948221879" y="1357.73148004447" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double value="0" />
    </CoreNodeModels.Input.DoubleInput>
    <Dynamo.Graph.Nodes.ZeroTouch.DSFunction guid="a02cfb15-97e8-48fa-8b9d-8019364b2ae1" type="Dynamo.Graph.Nodes.ZeroTouch.DSFunction" nickname="Point.ByCoordinates" x="3543.95336189675" y="1358.09099923262" isVisible="true" isUpstreamVisible="true" lacing="Shortest" isSelectedInput="False" IsFrozen="false" isPinned="false" assembly="ProtoGeometry.dll" function="Autodesk.DesignScript.Geometry.Point.ByCoordinates@double,double,double">
      <PortInfo index="0" default="True" />
      <PortInfo index="1" default="True" />
      <PortInfo index="2" default="True" />
    </Dynamo.Graph.Nodes.ZeroTouch.DSFunction>
    <PythonNodeModels.PythonNode guid="1ccd9d48-418f-4720-9e0c-3877ad34fe9b" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3554.71559981825" y="1899.91608782328" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

#Assign your output to the OUT variable.
OUT = 0</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.Input.DoubleInput guid="840b0d61-fa09-4282-b1e3-1d9da4a8d880" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="3427.62168848883" y="1895.76657404996" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double value="0" />
    </CoreNodeModels.Input.DoubleInput>
    <CoreNodeModels.Input.DoubleInput guid="f6075e74-86c6-4cd1-87cb-794ba0964639" type="CoreNodeModels.Input.DoubleInput" nickname="Number" x="3417.96088426502" y="1530.53841251389" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <System.Double value="0" />
    </CoreNodeModels.Input.DoubleInput>
    <PythonNodeModels.PythonNode guid="c36be87e-ea62-454d-8f48-79ce0dfc2a27" type="PythonNodeModels.PythonNode" nickname="Python Script" x="3545.05479559443" y="1534.68792628721" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *
#The inputs to this node will be stored as a list in the IN variables.
dataEnteringNode = IN

x = IN[0]
y = IN[1]
z = IN[2]

p = Point.ByCoordinates(x,y,z)
#Assign your output to the OUT variable.
OUT = p</Script>
    </PythonNodeModels.PythonNode>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="74d35359-3433-4163-be01-54e328bd06de" start_index="0" end="a02cfb15-97e8-48fa-8b9d-8019364b2ae1" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="74d35359-3433-4163-be01-54e328bd06de" start_index="0" end="a02cfb15-97e8-48fa-8b9d-8019364b2ae1" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="74d35359-3433-4163-be01-54e328bd06de" start_index="0" end="a02cfb15-97e8-48fa-8b9d-8019364b2ae1" end_index="2" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6075e74-86c6-4cd1-87cb-794ba0964639" start_index="0" end="c36be87e-ea62-454d-8f48-79ce0dfc2a27" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6075e74-86c6-4cd1-87cb-794ba0964639" start_index="0" end="c36be87e-ea62-454d-8f48-79ce0dfc2a27" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="f6075e74-86c6-4cd1-87cb-794ba0964639" start_index="0" end="c36be87e-ea62-454d-8f48-79ce0dfc2a27" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-2.65151453018188" eyeY="11.9353809356689" eyeZ="8.87096977233887" lookX="0.21070371568203" lookY="-5.07181596755981" lookZ="-3.44497513771057" upX="0.0213796496391296" upY="0.936672210693359" upZ="-0.349554181098938" />
  </Cameras>
</Workspace>